const cppProjects = [
  { n: 1, name: "Hello Universe", level: "Beginner", desc: "main()", slug: "01_hello_universe" },
  { n: 2, name: "Number Guess Duel", level: "Beginner", desc: "variables", slug: "02_number_guess_duel" },
  { n: 3, name: "FizzBuzz Jazz", level: "Beginner", desc: "for-loops", slug: "03_fizzbuzz_jazz" },
  { n: 4, name: "Temp Toggle Booth", level: "Beginner", desc: "functions", slug: "04_temp_toggle_booth" },
  { n: 5, name: "Caesar Shift Desk", level: "Beginner", desc: "chars", slug: "05_caesar_shift_desk" },
  { n: 6, name: "Dice Histogram", level: "Beginner", desc: "arrays", slug: "06_dice_histogram" },
  { n: 7, name: "Palindrome Patrol", level: "Beginner", desc: "string cleanup", slug: "07_palindrome_patrol" },
  { n: 8, name: "Prime Radar", level: "Beginner", desc: "nested loops", slug: "08_prime_radar" },
  { n: 9, name: "Rock Paper CPU", level: "Beginner", desc: "enums-as-ints", slug: "09_rock_paper_cpu" },
  { n: 10, name: "Word Counter Desk", level: "Beginner", desc: "stringstream", slug: "10_word_counter_desk" },
  { n: 11, name: "Password Strength Gage", level: "Beginner", desc: "char classification", slug: "11_password_strength_gage" },
  { n: 12, name: "Tip Splitter", level: "Beginner", desc: "doubles", slug: "12_tip_splitter" },
  { n: 13, name: "Fibonacci Fountain", level: "Beginner", desc: "iteration", slug: "13_fibonacci_fountain" },
  { n: 14, name: "Morse Blink Desk", level: "Beginner", desc: "lookup tables with std::map", slug: "14_morse_blink_desk" },
  { n: 15, name: "Grade Curve Lab", level: "Beginner", desc: "vectors", slug: "15_grade_curve_lab" },
  { n: 16, name: "Anagram Detective", level: "Beginner", desc: "algorithms sort", slug: "16_anagram_detective" },
  { n: 17, name: "Vector Stats Bench", level: "Intermediate", desc: "STL algorithms", slug: "17_vector_stats_bench" },
  { n: 18, name: "Stack Undo Buffer", level: "Intermediate", desc: "std::stack", slug: "18_stack_undo_buffer" },
  { n: 19, name: "Queue Hot Potato", level: "Intermediate", desc: "std::queue", slug: "19_queue_hot_potato" },
  { n: 20, name: "Struct Contact Book", level: "Intermediate", desc: "structs", slug: "20_struct_contact_book" },
  { n: 21, name: "Binary Search Tracer", level: "Intermediate", desc: "divide-and-conquer", slug: "21_binary_search_tracer" },
  { n: 22, name: "Bubble Sort Stage", level: "Intermediate", desc: "nested loops", slug: "22_bubble_sort_stage" },
  { n: 23, name: "Class Pet Zoo", level: "Intermediate", desc: "classes", slug: "23_class_pet_zoo" },
  { n: 24, name: "Template Toolkit", level: "Intermediate", desc: "function templates", slug: "24_template_toolkit" },
  { n: 25, name: "File Haiku Logger", level: "Intermediate", desc: "fstream", slug: "25_file_haiku_logger" },
  { n: 26, name: "CSV Mini Reader", level: "Intermediate", desc: "stringstream tokenization", slug: "26_csv_mini_reader" },
  { n: 27, name: "Pointer Treasure Map", level: "Intermediate", desc: "raw pointers", slug: "27_pointer_treasure_map" },
  { n: 28, name: "Enum Traffic Light", level: "Intermediate", desc: "enum class", slug: "28_enum_traffic_light" },
  { n: 29, name: "Lambda Sort Party", level: "Intermediate", desc: "lambdas", slug: "29_lambda_sort_party" },
  { n: 30, name: "Optional Treasure", level: "Intermediate", desc: "std::optional", slug: "30_optional_treasure" },
  { n: 31, name: "PPM Pixel Banner", level: "Advanced", desc: "file binary/text formats", slug: "31_ppm_pixel_banner" },
  { n: 32, name: "Game of Life Seed", level: "Advanced", desc: "2D grids", slug: "32_game_of_life_seed" },
  { n: 33, name: "Recursive Maze Escape", level: "Advanced", desc: "recursion", slug: "33_recursive_maze_escape" },
  { n: 34, name: "BFS Shortcut City", level: "Advanced", desc: "graphs as adjacency lists", slug: "34_bfs_shortcut_city" },
  { n: 35, name: "Smart Pointer Garage", level: "Advanced", desc: "unique_ptr", slug: "35_smart_pointer_garage" },
  { n: 36, name: "Thread Lap Timer", level: "Advanced", desc: "std::thread", slug: "36_thread_lap_timer" },
  { n: 37, name: "Regex Token Scanner", level: "Advanced", desc: "regular expressions", slug: "37_regex_token_scanner" },
  { n: 38, name: "Variant Shape Bag", level: "Advanced", desc: "std::variant", slug: "38_variant_shape_bag" },
  { n: 39, name: "Move Semantics Relay", level: "Advanced", desc: "move ctor", slug: "39_move_semantics_relay" },
  { n: 40, name: "Constexpr Magic Square", level: "Advanced", desc: "constexpr functions", slug: "40_constexpr_magic_square" }
];
